### ISSUE TITLE
When initially launching gatorgrade in a repo with a gatorgrade.yml file, there is an Type Error with the command.

### ISSUE THREAD

**Issue by AlmostFaultTolerant** [GatorEducator/gatorgrade#104]
When attempting this command inside a repo with a gatorgrade.yml file; "gatorgrade --config config/gatorgrade.yml" , there was the following error:
```
Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\Scripts\gatorgrade.exe\__main__.py", line 4, in <module>
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\gatorgrade\main.py", line 36, in <module>
    root: Path = typer.Argument(
TypeError: Argument() got an unexpected keyword argument 'help'
```
Uninstalling and reinstalling gatorgrade through pipx didn't fix it.  Trying to shorten the command by going inside the file with the gatorgrade.yml file yielded the same results. On Windows 11 Pro.

**Comment by gkapfham** [comment]
Hello @AlmostFaultTolerant, thanks for raising this issue!

Could you please show the specific version that you are using of these programs?

- Python
- Poetry
- Pip
- Pipx

Can you also please explain what directory you are running the `gatorgrade` command from and what the project layout looks like?

Thanks for sharing these extra details as I look forward to using them to resolve this issue.

:smile:

**Comment by AlmostFaultTolerant** [comment]
Sure thing!
Python - 3.10.2
Poetry - 1.2.0
Pip - 22.2.2
Pipx - 1.1.0
I don't have any other versions of Python on my computer, and I ran the command from here:
C:\Users\me\Documents\CMPSC\CMPSC_101\computer-science-101-fall-2022-ee1-integer-squaring-AlmostFaultTolerant>
Finally, I have around 10 environment variables under Path, so I'll include the one with gradle in the location:
C:\Gradle\gradle-7.4\bin

**Comment by gkapfham** [comment]
We have not had any recent reports of this issue on Windows and there were no reports of it on any other operating systems and thus I am going to close this issue.
